// productsData.ts

export const oilChangeProducts = [
  {
    id: "1",
    imgSrc: "/images/oil1.jpeg",
    title: "Synthetic Motor Oil 5W-30",
    description: "Premium engine protection and performance.",
    features: [
      "Extended drain intervals",
      "Improved fuel efficiency",
      "Reduces engine wear",
    ],
    price: "$35",
    supplier: "Supplier X",
    rating: 4.6,
    reviews: 88,
  },
  {
    id: "2",
    imgSrc: "/images/oil2.jpeg",
    title: "Oil Filter Wrench",
    description: "Easily remove oil filters with adjustable grip.",
    features: [
      "Non-slip handle",
      "Fits most filters",
      "Durable steel construction",
    ],
    price: "$15",
    supplier: "Supplier Y",
    rating: 4.4,
    reviews: 52,
  },
  {
    id: "3",
    imgSrc: "/images/oil3.jpeg",
    title: "Drain Pan 12L",
    description: "Large capacity oil drain pan for clean disposal.",
    features: ["Spill-proof design", "Easy pour spout", "Chemical-resistant"],
    price: "$22",
    supplier: "Supplier Z",
    rating: 4.7,
    reviews: 64,
  },
  {
    id: "4",
    imgSrc: "/images/oil4.jpeg",
    title: "Oil Filter Cartridge",
    description: "High-quality filtration for longer engine life.",
    features: [
      "OEM fit",
      "Extended service intervals",
      "Anti-drain back valve",
    ],
    price: "$12",
    supplier: "AutoParts Co.",
    rating: 4.5,
    reviews: 39,
  },
  {
    id: "5",
    imgSrc: "/images/oil5.jpeg",
    title: "Oil Funnel Set",
    description: "Mess-free oil changes with multiple sizes.",
    features: ["Flexible design", "Multiple attachments", "Durable plastic"],
    price: "$10",
    supplier: "ToolZone",
    rating: 4.3,
    reviews: 27,
  },
  {
    id: "6",
    imgSrc: "/images/oil6.jpeg",
    title: "Oil Change Kit",
    description: "Complete kit with oil, filter, and tools.",
    features: ["All-in-one solution", "Top brand oil", "Includes gloves"],
    price: "$49",
    supplier: "QuickFix",
    rating: 4.6,
    reviews: 72,
  },
];

export const brakeProducts = [
  {
    id: "1",
    imgSrc: "/images/brake1.jpeg",
    title: "Ceramic Brake Pads",
    description: "Smooth stopping power with minimal dust.",
    features: ["Low noise", "Long-lasting", "OE fit"],
    price: "$45",
    supplier: "BrakeCo",
    rating: 4.5,
    reviews: 98,
  },
  {
    id: "2",
    imgSrc: "/images/brake2.jpeg",
    title: "Brake Fluid DOT 4",
    description: "High-performance fluid for responsive braking.",
    features: [
      "Boiling point 446°F",
      "Corrosion protection",
      "Compatible with ABS",
    ],
    price: "$12",
    supplier: "Supplier Z",
    rating: 4.3,
    reviews: 34,
  },
  {
    id: "3",
    imgSrc: "/images/brake3.jpeg",
    title: "Brake Caliper Tool Kit",
    description: "Makes caliper retraction fast and easy.",
    features: ["Multiple adapters", "Heavy-duty case", "Universal use"],
    price: "$30",
    supplier: "ToolsPro",
    rating: 4.6,
    reviews: 41,
  },
  {
    id: "4",
    imgSrc: "/images/brake4.jpeg",
    title: "Brake Rotors Pair",
    description: "Precision-balanced rotors for smooth braking.",
    features: ["Rust-resistant coating", "Direct fit", "Low vibration"],
    price: "$85",
    supplier: "DiscMaster",
    rating: 4.4,
    reviews: 60,
  },
  {
    id: "5",
    imgSrc: "/images/brake5.jpeg",
    title: "Brake Bleeder Kit",
    description: "Effortless bleeding for firm brakes.",
    features: [
      "One-person operation",
      "Includes hoses and bottle",
      "Universal adapter",
    ],
    price: "$25",
    supplier: "FixTech",
    rating: 4.2,
    reviews: 33,
  },
  {
    id: "6",
    imgSrc: "/images/brake6.jpeg",
    title: "Brake Line Replacement Set",
    description: "Stainless steel brake lines for better response.",
    features: ["Corrosion-resistant", "Exact fit", "DOT approved"],
    price: "$110",
    supplier: "SteelFlow",
    rating: 4.7,
    reviews: 48,
  },
];

export const tireProducts = [
  {
    id: "1",
    imgSrc: "/images/tire1.jpeg",
    title: "All-Season Radial Tire",
    description: "Durable tires for year-round performance.",
    features: ["Hydroplaning resistance", "Quiet ride", "Fuel-efficient tread"],
    price: "$89",
    supplier: "TireHub",
    rating: 4.7,
    reviews: 101,
  },
  {
    id: "2",
    imgSrc: "/images/tire2.jpeg",
    title: "Tire Inflator with Gauge",
    description: "Compact tool for accurate pressure check.",
    features: ["Easy-read dial", "Auto shut-off", "LED light"],
    price: "$35",
    supplier: "Supplier B",
    rating: 4.5,
    reviews: 67,
  },
  {
    id: "3",
    imgSrc: "/images/tire3.jpeg",
    title: "Tire Rotation Stand",
    description: "Convenient stand for at-home tire rotation.",
    features: ["Heavy-duty frame", "Slip-resistant base", "Easy to use"],
    price: "$60",
    supplier: "AutoTools",
    rating: 4.4,
    reviews: 38,
  },
  {
    id: "4",
    imgSrc: "/images/tire4.jpeg",
    title: "Digital Tire Pressure Gauge",
    description: "Instant, accurate readings in any condition.",
    features: ["Backlit screen", "Compact", "Auto shut-off"],
    price: "$18",
    supplier: "TireTools",
    rating: 4.6,
    reviews: 90,
  },
  {
    id: "5",
    imgSrc: "/images/tire5.jpeg",
    title: "Tire Patch Kit",
    description: "Quick fix for punctured tires.",
    features: ["Rubber cement", "Patches included", "Easy instructions"],
    price: "$10",
    supplier: "PatchIt",
    rating: 4.3,
    reviews: 40,
  },
  {
    id: "6",
    imgSrc: "/images/tire6.jpeg",
    title: "Tire Balancing Weights",
    description: "Ensure even weight distribution for smooth rides.",
    features: ["Lead-free", "Peel and stick", "Multiple sizes"],
    price: "$22",
    supplier: "BalancePro",
    rating: 4.2,
    reviews: 35,
  },
];

export const engineProducts = [
  {
    id: "1",
    imgSrc: "/images/diagnostic1.jpeg",
    title: "OBD-II Scanner",
    description: "Quickly identify engine fault codes with precision.",
    features: [
      "Compact design",
      "Reads multiple fault codes",
      "User-friendly interface",
    ],
    price: "$120",
    supplier: "Supplier A",
    rating: 4.5,
    reviews: 74,
  },
  {
    id: "2",
    imgSrc: "/images/diagnostic2.jpeg",
    title: "Digital Compression Tester",
    description: "Accurately measure engine compression levels.",
    features: [
      "Digital display",
      "Quick-connect hose",
      "Multiple adapters included",
    ],
    price: "$95",
    supplier: "Supplier A",
    rating: 4.2,
    reviews: 56,
  },
  {
    id: "3",
    imgSrc: "/images/diagnostic3.jpeg",
    title: "Engine Analyzer",
    description: "Advanced analysis for performance and fault detection.",
    features: [
      "Real-time data",
      "High-resolution display",
      "Wide compatibility",
    ],
    price: "$250",
    supplier: "Supplier B",
    rating: 4.7,
    reviews: 92,
  },
  {
    id: "4",
    imgSrc: "/images/engine4.jpeg",
    title: "Spark Plug Tester",
    description: "Quickly test spark strength in ignition systems.",
    features: ["LED indicator", "Works with 6V–12V systems", "Durable"],
    price: "$20",
    supplier: "IgniteCo",
    rating: 4.3,
    reviews: 45,
  },
  {
    id: "5",
    imgSrc: "/images/engine5.jpeg",
    title: "Vacuum Gauge Kit",
    description: "Diagnose leaks and tune your engine.",
    features: ["Easy to read", "Mounting hardware included", "Universal"],
    price: "$35",
    supplier: "EngineTech",
    rating: 4.4,
    reviews: 36,
  },
  {
    id: "6",
    imgSrc: "/images/engine6.jpeg",
    title: "Timing Light",
    description: "Set ignition timing for better performance.",
    features: ["Xenon flash", "Works with most engines", "Durable build"],
    price: "$50",
    supplier: "TuneTools",
    rating: 4.6,
    reviews: 63,
  },
];

// If you'd like me to finish battery and airConditioning too — just say the word.
export const batteryProducts = [
  {
    id: "1",
    imgSrc: "/images/battery1.jpeg",
    title: "Car Battery 12V 60Ah",
    description: "Reliable power for modern vehicles.",
    features: ["Maintenance-free", "High cold cranking amps", "Long life"],
    price: "$110",
    supplier: "PowerCell",
    rating: 4.6,
    reviews: 70,
  },
  {
    id: "2",
    imgSrc: "/images/battery2.jpeg",
    title: "Battery Terminal Cleaner",
    description: "Removes corrosion for better conductivity.",
    features: ["Brush and reamer", "Ergonomic grip", "Universal size"],
    price: "$9",
    supplier: "ToolEase",
    rating: 4.4,
    reviews: 38,
  },
  {
    id: "3",
    imgSrc: "/images/battery3.jpeg",
    title: "Battery Charger 12V",
    description: "Fast and safe battery charging solution.",
    features: ["Overcharge protection", "Automatic shutoff", "Digital display"],
    price: "$65",
    supplier: "ChargeMaster",
    rating: 4.7,
    reviews: 89,
  },
  {
    id: "4",
    imgSrc: "/images/battery4.jpeg",
    title: "Battery Load Tester",
    description: "Check battery condition with accuracy.",
    features: ["Digital readout", "Easy-to-use clips", "Compact design"],
    price: "$30",
    supplier: "VoltCheck",
    rating: 4.5,
    reviews: 54,
  },
  {
    id: "5",
    imgSrc: "/images/battery5.jpeg",
    title: "Jump Starter Pack",
    description: "Start your vehicle anytime, anywhere.",
    features: ["USB charging", "LED flashlight", "Compact and powerful"],
    price: "$90",
    supplier: "BoostNow",
    rating: 4.8,
    reviews: 120,
  },
  {
    id: "6",
    imgSrc: "/images/battery6.jpeg",
    title: "Battery Terminal Kit",
    description: "Replace corroded terminals with ease.",
    features: ["Brass connectors", "Color coded", "Corrosion resistant"],
    price: "$12",
    supplier: "AutoElectro",
    rating: 4.3,
    reviews: 41,
  },
];

export const airConditioningProducts = [
  {
    id: "1",
    imgSrc: "/images/air1.jpeg",
    title: "AC Recharge Kit",
    description: "Restore cold air with easy DIY refill.",
    features: [
      "R134a compatible",
      "Pressure gauge included",
      "No tools required",
    ],
    price: "$35",
    supplier: "CoolAir",
    rating: 4.6,
    reviews: 83,
  },
  {
    id: "2",
    imgSrc: "/images/air2.jpeg",
    title: "Cabin Air Filter",
    description: "Keep air clean and fresh inside your car.",
    features: [
      "Traps dust and pollen",
      "Easy installation",
      "Lasts up to 15,000 miles",
    ],
    price: "$18",
    supplier: "FilterPro",
    rating: 4.5,
    reviews: 60,
  },
  {
    id: "3",
    imgSrc: "/images/air3.jpeg",
    title: "AC Leak Detector",
    description: "Quickly spot refrigerant leaks.",
    features: ["UV dye included", "High accuracy", "Simple to use"],
    price: "$25",
    supplier: "Detecto",
    rating: 4.4,
    reviews: 47,
  },
  {
    id: "4",
    imgSrc: "/images/air4.jpeg",
    title: "AC Compressor Oil",
    description: "Lubricates and protects AC systems.",
    features: ["Compatible with PAG", "Anti-wear formula", "Long-lasting"],
    price: "$12",
    supplier: "LubraMax",
    rating: 4.2,
    reviews: 33,
  },
  {
    id: "5",
    imgSrc: "/images/air5.jpeg",
    title: "AC Compressor Pulley",
    description: "High-quality pulley for smooth operation.",
    features: ["OEM grade", "Precision bearing", "Quiet performance"],
    price: "$55",
    supplier: "PulleyTech",
    rating: 4.3,
    reviews: 29,
  },
  {
    id: "6",
    imgSrc: "/images/air6.jpeg",
    title: "Refrigerant Pressure Gauge Set",
    description: "Monitor system pressure like a pro.",
    features: ["Color-coded dials", "Durable hoses", "Easy-to-read gauges"],
    price: "$40",
    supplier: "ACTools",
    rating: 4.7,
    reviews: 68,
  },
];

export const allProducts = {
  oilChangeProducts,
  brakeProducts,
  tireProducts,
  engineProducts,
  batteryProducts,
  airConditioningProducts,
};
