import type { Metadata } from "next";
import "../globals.css";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import HorizontalScroll from "../../components/HorizontalScroll";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const services = [
    {
      title: "Oil Change",
      icon: "🛢️",
      link: "/services/oilchange",
    },
    {
      title: "Brake Repair",
      icon: "🚗",
      link: "/services/brakes",
    },
    {
      title: "Tire Services",
      icon: "🚙",
      link: "/services/tires",
    },
    {
      title: "Engine Diagnostics",
      icon: "🔧",
      link: "/services/engine",
    },
    {
      title: "Battery Replacement",
      icon: "🔋",
      link: "/services/batteries",
    },
    {
      title: "Air Conditioning",
      icon: "❄️",
      link: "/services/air",
    },
    {
      title: "Tire Services",
      icon: "🚙",
      link: "/services/tires",
    },
    {
      title: "Engine Diagnostics",
      icon: "🔧",
      link: "/services/engine",
    },
    {
      title: "Battery Replacement",
      icon: "🔋",
      link: "/services/batteries",
    },
    {
      title: "Air Conditioning",
      icon: "❄️",
      link: "/services/air",
    },
    {
      title: "Oil Change",
      icon: "🛢️",
      link: "/services/oilchange",
    },
    {
      title: "Brake Repair",
      icon: "🚗",
      link: "/services/brakes",
    },
    {
      title: "Tire Services",
      icon: "🚙",
      link: "/services/tires",
    },
    {
      title: "Engine Diagnostics",
      icon: "🔧",
      link: "/services/engine",
    },
  ];

  return (
   <div>

<Header />
<HorizontalScroll items={services} />
        {children}
        <Footer />
   </div>
     
  );
}
