// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Chat from "@/components/Chat";
import Cart from "@/components/Cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Chat />
        <Cart />
      </body>
    </html>
  );
}